name: Build and Test

on:
  push:
    branches: [practice_3]
  pull_request:
    branches: [practice_3]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: practice_3  

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make debhelper dpkg-dev libgtest-dev

      - name: Build project
        run: |
          make all

      - name: Run tests
        run: |
          make test
          ./usr/test_fibonacci

      - name: Create .deb package
        run: |
          make package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fibonacci_deb_package
          path: fibonacci.deb

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: fibonacci_deb_package

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ekaterinashliakhova/fibonacci:latest .

      - name: Push Docker image
        run: |
          docker push ekaterinashliakhova/fibonacci:latest
