name: C/C++ CI

on:
  push:
    branches: [ practice_2 ]
  pull_request:
    branches: [ practice_2 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v1.0
    - name: build application
      run: make all